input1=float(input("Enter the first number:"))
input2=float(input("Enter the second number:"))
print("Addition:",input1+input2)
print("Substraction:",input1-input2)
print("Multiplication:",input1*input2)
print("Division:",input1/input2)
